# Generated by Django 4.2.30 on 2026-05-28 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_add_estado_cliente_motocicleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_cu', models.CharField(max_length=20)),
                ('nombre_modulo', models.CharField(max_length=255)),
                ('accion', models.CharField(max_length=50)),
                ('permitido', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'permiso_modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('tipo_gestion', models.CharField(max_length=50)),
                ('canal', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.cliente')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='taller.usuario')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
    ]
