# Generated by Django 4.2.30 on 2026-05-30 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_permisomodulo_seguimiento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'managed': True},
        ),
    ]
