import os
import socket
from urllib.parse import urlparse

# Algunos proveedores de hosting (Render incluido) no enrutan bien IPv6 saliente,
# y Gmail SMTP a veces resuelve primero a una direccion IPv6, causando
# "[Errno 101] Network is unreachable". Forzamos resolucion DNS solo IPv4.
_getaddrinfo_original = socket.getaddrinfo


def _getaddrinfo_solo_ipv4(host, port, family=0, type=0, proto=0, flags=0):
    return _getaddrinfo_original(host, port, socket.AF_INET, type, proto, flags)


socket.getaddrinfo = _getaddrinfo_solo_ipv4
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

def load_dotenv_file(path):
    try:
        with open(path, encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                if '=' not in line:
                    continue
                key, value = line.split('=', 1)
                key = key.strip()
                value = value.strip()
                if len(value) >= 2 and ((value[0] == value[-1] == '"') or (value[0] == value[-1] == "'")):
                    value = value[1:-1]
                if key and key not in os.environ:
                    os.environ[key] = value
    except FileNotFoundError:
        pass

# Load .env from the repository root when running locally.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv_file(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def get_bool_env(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_bool_env('DJANGO_DEBUG', True)

WEBSITE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', 'localhost').strip()
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000').strip()

def build_origin(url):
    parsed = urlparse(url)
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return ''

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]
if not ALLOWED_HOSTS:
    if WEBSITE_HOSTNAME == 'localhost':
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']
    else:
        # Añadimos el comodín '*' para permitir los pings de salud de la red interna de Azure
        ALLOWED_HOSTS = [WEBSITE_HOSTNAME, '*']

CSRF_TRUSTED_ORIGINS = []
frontend_origin = build_origin(FRONTEND_URL)
if frontend_origin:
    CSRF_TRUSTED_ORIGINS.append(frontend_origin)

if WEBSITE_HOSTNAME == 'localhost':
    CSRF_TRUSTED_ORIGINS.extend(['http://localhost', 'http://127.0.0.1'])
else:
    CSRF_TRUSTED_ORIGINS.append(f"https://{WEBSITE_HOSTNAME}")

TOKEN_MAX_AGE_SECONDS = int(os.environ.get('TOKEN_MAX_AGE_SECONDS', '3600'))
CLIENT_TEMP_PASSWORD = os.environ.get('CLIENT_TEMP_PASSWORD', 'zaq12wsx')
PASSWORD_RESET_TOKEN_MAX_AGE_SECONDS = int(os.environ.get('PASSWORD_RESET_TOKEN_MAX_AGE_SECONDS', '1800'))
PASSWORD_RESET_LIMIT_PER_IP = int(os.environ.get('PASSWORD_RESET_LIMIT_PER_IP', '20'))
PASSWORD_RESET_LIMIT_PER_EMAIL = int(os.environ.get('PASSWORD_RESET_LIMIT_PER_EMAIL', '5'))
PASSWORD_RESET_WINDOW_SECONDS = int(os.environ.get('PASSWORD_RESET_WINDOW_SECONDS', '3600'))
PASSWORD_RESET_CODE_MAX_AGE_SECONDS = int(os.environ.get('PASSWORD_RESET_CODE_MAX_AGE_SECONDS', '600'))
PASSWORD_RESET_CODE_MAX_ATTEMPTS = int(os.environ.get('PASSWORD_RESET_CODE_MAX_ATTEMPTS', '5'))
FRONTEND_URL = FRONTEND_URL
MAIL_MODE = os.environ.get('MAIL_MODE', 'offline').strip().lower()
PASSWORD_RESET_LOG_TO_CONSOLE = get_bool_env('PASSWORD_RESET_LOG_TO_CONSOLE', True)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT_SECONDS', '15'))
EMAIL_SEND_RETRIES = int(os.environ.get('EMAIL_SEND_RETRIES', '3'))

BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()

if MAIL_MODE == 'online':
    EMAIL_HOST = os.environ.get('MAIL_ONLINE_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('MAIL_ONLINE_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('MAIL_ONLINE_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('MAIL_ONLINE_PASSWORD', '')
    EMAIL_USE_TLS = get_bool_env('MAIL_ONLINE_USE_TLS', True)
    EMAIL_USE_SSL = get_bool_env('MAIL_ONLINE_USE_SSL', False)
    DEFAULT_FROM_EMAIL = f"TALLER DE MOTOS - LA ROCA <{os.environ.get('MAIL_ONLINE_FROM_EMAIL', EMAIL_HOST_USER or 'acovi2014@gmail.com')}>"
    MAIL_ONLINE_TEST_INBOX = os.environ.get('MAIL_ONLINE_TEST_INBOX', 'teteryu79e@gmail.com').strip().lower()
    # Si hay API key de Brevo, manda por HTTPS (Render bloquea los puertos SMTP).
    # Si no, cae al SMTP normal (funciona bien en local).
    if BREVO_API_KEY:
        EMAIL_BACKEND = 'taller.email_backend.BrevoApiEmailBackend'
    else:
        EMAIL_BACKEND = os.environ.get('MAIL_ONLINE_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
else:
    EMAIL_BACKEND = os.environ.get('MAIL_OFFLINE_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.environ.get('MAIL_OFFLINE_HOST', 'mailpit')
    EMAIL_PORT = int(os.environ.get('MAIL_OFFLINE_PORT', '1025'))
    EMAIL_HOST_USER = os.environ.get('MAIL_OFFLINE_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('MAIL_OFFLINE_PASSWORD', '')
    EMAIL_USE_TLS = get_bool_env('MAIL_OFFLINE_USE_TLS', False)
    EMAIL_USE_SSL = get_bool_env('MAIL_OFFLINE_USE_SSL', False)
    DEFAULT_FROM_EMAIL = f"TALLER DE MOTOS - LA ROCA <{os.environ.get('MAIL_OFFLINE_FROM_EMAIL', 'taller@laroca.com')}>"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'cloudinary',
    'rest_framework',  # <--- Agregado para el Frontend
    'taller',          # <--- Tu nueva App
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'db_taller_motos'),
        'USER': os.environ.get('DB_USER', 'usuario_taller'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Archivos subidos por usuarios (ej. comprobantes de pago)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Si hay credenciales de Cloudinary, los archivos subidos (comprobantes de pago)
# se guardan ahi en vez del disco local. Render borra el disco local en cada
# deploy, asi que sin esto los comprobantes se perderian.
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '').strip()
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '').strip()
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '').strip()

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# PayPal (pago en linea del cliente desde su perfil)
PAYPAL_MODE = os.environ.get('PAYPAL_MODE', 'sandbox').strip().lower()
PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID', '')
PAYPAL_SECRET = os.environ.get('PAYPAL_SECRET', '')
PAYPAL_API_BASE = (
    'https://api-m.paypal.com' if PAYPAL_MODE == 'live' else 'https://api-m.sandbox.paypal.com'
)

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Permite que el Frontend de React pase la aduana del servidor
CORS_ALLOW_ALL_ORIGINS = True