from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from taller.views import (
    debug_login,
    login_api,
    bitacora_api,
    usuarios_api,
    usuario_detalle_api,
    usuario_vincular_cliente_api,
    roles_api,
    rol_detalle_api,
    privilegios_api,
    privilegio_detalle_api,
    roles_privilegios_api,
    clientes_api,
    cliente_detalle_api,
    motocicletas_api,
    motocicleta_detalle_api,
    mis_motocicletas_api,
    mis_motocicletas_historial_api,
    proveedores_api,
    proveedor_detalle_api,
    productos_api,
    producto_detalle_api,
    inventario_api,
    compras_api,
    cotizaciones_api,
    cotizacion_detalle_api,
    ordenes_trabajo_api,
    orden_trabajo_detalle_api,
    notas_trabajo_api,
    nota_trabajo_detalle_api,
    perfil_api,
    force_change_password_api,
    forgot_password_request_api,
    reset_password_confirm_api,
    verify_reset_code_api,
    registro_api,
    verify_register_code_api,
    resend_register_code_api,
    aceptar_cotizacion_api,
    logout_api,
    permisos_api,
    facturacion_api,
    facturacion_historial_api,
    mis_pagos_api,
    mis_pagos_qr_api,
    mis_pagos_paypal_crear_api,
    mis_pagos_paypal_capturar_api,
    HistorialMantenimientoAPI,
    SeguimientoClientesAPI,
    reportes_api,
    dashboard_api,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    # Debug endpoint
    path('api/debug/login/', debug_login, name='api_debug_login'),
    # Ruta para el CU01
    path('api/login/', login_api, name='api_login'),
    path('api/password/forgot/', forgot_password_request_api, name='api_password_forgot'),
    path('api/password/verify-code/', verify_reset_code_api, name='api_password_verify_code'),
    path('api/password/reset/', reset_password_confirm_api, name='api_password_reset'),
    path('api/password/force-change/', force_change_password_api, name='api_password_force_change'),
    path('api/register/', registro_api, name='api_register'),
    path('api/register/verify/', verify_register_code_api, name='api_register_verify'),
    path('api/register/resend/', resend_register_code_api, name='api_register_resend'),
    path('api/logout/', logout_api, name='api_logout'),
    # Ruta para el CU20
    path('api/bitacora/', bitacora_api, name='api_bitacora'),
    # NUEVAS RUTAS FASE B:
    path('api/usuarios/', usuarios_api, name='api_usuarios'),
    path('api/usuarios/<int:usuario_id>/', usuario_detalle_api, name='api_usuario_detalle'),
    path('api/usuarios/<int:usuario_id>/vincular-cliente/', usuario_vincular_cliente_api, name='api_usuario_vincular_cliente'),
    path('api/roles/', roles_api, name='api_roles'),
    path('api/roles/<int:rol_id>/', rol_detalle_api, name='api_rol_detalle'),
    path('api/privilegios/', privilegios_api, name='api_privilegios'),
    path('api/privilegios/<int:privilegio_id>/', privilegio_detalle_api, name='api_privilegio_detalle'),
    path('api/roles-privilegios/', roles_privilegios_api, name='api_roles_privilegios'),
    path('api/clientes/', clientes_api, name='api_clientes'),
    path('api/clientes/<int:cliente_id>/', cliente_detalle_api, name='api_cliente_detalle'),
    path('api/motocicletas/', motocicletas_api, name='api_motocicletas'),
    path('api/motocicletas/<int:motocicleta_id>/', motocicleta_detalle_api, name='api_motocicleta_detalle'),
    path('api/mis-motocicletas/', mis_motocicletas_api, name='api_mis_motocicletas'),
    path('api/mis-motocicletas/<int:moto_id>/historial/', mis_motocicletas_historial_api, name='api_mis_motocicletas_historial'),
    path('api/proveedores/', proveedores_api, name='api_proveedores'),
    path('api/proveedores/<int:proveedor_id>/', proveedor_detalle_api, name='api_proveedor_detalle'),
    path('api/productos/', productos_api, name='api_productos'),
    path('api/productos/<int:producto_id>/', producto_detalle_api, name='api_producto_detalle'),
    path('api/inventario/', inventario_api, name='api_inventario'),
    path('api/compras/', compras_api, name='api_compras'),
    path('api/cotizaciones/', cotizaciones_api, name='api_cotizaciones'),
    path('api/cotizaciones/<int:cotizacion_id>/', cotizacion_detalle_api, name='api_cotizacion_detalle'),
    path('api/ordenes-trabajo/', ordenes_trabajo_api, name='api_ordenes_trabajo'),
    path('api/ordenes-trabajo/<int:orden_id>/', orden_trabajo_detalle_api, name='api_orden_trabajo_detalle'),
    path('api/notas-trabajo/', notas_trabajo_api, name='api_notas_trabajo'),
    path('api/notas-trabajo/<int:nota_id>/', nota_trabajo_detalle_api, name='api_nota_trabajo_detalle'),
    path('api/perfil/', perfil_api, name='api_perfil'),
    path('api/cotizaciones/<int:cotizacion_id>/aceptar/', aceptar_cotizacion_api, name='api_cotizacion_aceptar'),
    path('api/permisos/', permisos_api, name='api_permisos'),
    path('api/facturacion/', facturacion_api, name='api_facturacion'),
    path('api/facturacion/historial/', facturacion_historial_api, name='api_facturacion_historial'),
    path('api/mis-pagos/', mis_pagos_api, name='api_mis_pagos'),
    path('api/mis-pagos/qr/', mis_pagos_qr_api, name='api_mis_pagos_qr'),
    path('api/mis-pagos/paypal/crear-orden/', mis_pagos_paypal_crear_api, name='api_mis_pagos_paypal_crear'),
    path('api/mis-pagos/paypal/capturar/', mis_pagos_paypal_capturar_api, name='api_mis_pagos_paypal_capturar'),
    path('api/historial-mantenimiento/', HistorialMantenimientoAPI.as_view(), name='api_historial_mantenimiento'),
    path('api/historial-mantenimiento/<int:orden_id>/', HistorialMantenimientoAPI.as_view(), name='api_historial_mantenimiento_detalle'),
    path('api/historial-mantenimiento/reporte/', HistorialMantenimientoAPI.as_view(), name='api_historial_mantenimiento_reporte'),
    path('api/seguimiento/', SeguimientoClientesAPI.as_view(), name='api_seguimiento'),
    path('api/seguimiento-clientes/', SeguimientoClientesAPI.as_view(), name='api_seguimiento_clientes'),
    path('api/reportes/', reportes_api, name='api_reportes'),
    path('api/dashboard/', dashboard_api, name='api_dashboard'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)